---
- hosts: myserver
  become: yes
  become_user: root
  tasks:
  - name: Install NTP Server
    yum: name=ntp state=latest
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^#restrict' line='restrict 192.168.100.1 mask 255.255.255.0 nomodify notrap' 
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 0.centos' line='server 0.th.pool.ntp.org iburst' 
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 1.centos' line='server 2.asia.pool.ntp.org iburst' 
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 2.centos' line='server 3.asia.pool.ntp.org iburst' 
  - name:
    lineinfile: path=/etc/ntp.conf regexp='^server 3.centos' line=' '  
  - name: Install firewalld
    yum: name=firewalld state=latest
  - name: Start firewalld
    service: name=firewalld state=started
  - name: Open firewall
    firewalld: service=ntp permanent=yes state=enabled
  - name: Restart firewalld
    service: name=firewalld state=restarted
  - name: set timezone to Asia/Bangkok
    timezone: name=Asia/Bangkok